# 工作流名称
name: CI & CD
# 触发条件
on:
  # 触发操作
  push:
    # 触发分支
    branches:
      - main
      - dev
      - "hotfix-**"
    # 触发目录
    paths:
      - "projects/**"
# 任务
jobs:
  CI:
    # 运行环境
    runs-on: ubuntu-latest
    # 超时时间
    timeout-minutes: 5
    # 步骤
    steps:
      # 使用actions
      # 校验yml是否有语法错误
      - uses: actions/checkout@v3
      # action：安装node
      - uses: actions/setup-node@v3
        # action 参数
        with:
          node-version: 19
      # 命令名称（非必须）
      - name: Install pnpm
        # 安装pnpm
        uses: pnpm/action-setup
        with:
          version: latest
        # 执行命令
      # - name: Deploy
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     REMOTE_USER: ${{ secrets.ROOT }}
      #     REMOTE_HOST: ${{ secrets.SERVER_IP }}
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ROOT }}
      #     ARGS: "-rltgoDzvO"
      #     SOURCE: "dist/"
      #     TARGET: "/var/www/repo/"
      #     EXCLUDE: "/dist/, /node_modules/"
  # CD:
  #   runs-on: ubuntu-latest
  #   needs: CI
  #   steps:
  # CI任务构建完成后, 不会保留dist文件, CD任务里找不到dist
  # ================ 需要先上传构建产物，再在其他任务中下载构建产物
  #     # 上传构建产物
  #     - name: Upload artifacts
  #       uses: actions/upload-artifact
  #       with:
  #         # 构建产物目录名称
  #         name: dist
  #         # 上传到哪个目录下
  #         path: bin
  #     # 下载构建产物
  #     - name: Download artifacts
  #       uses: actions/download-artifact
  #       with:
  #         name: dist
  #         path: bin
  #     - name: Deploy
  #       uses: easingthemes/ssh-deploy@main
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ROOT }}
  #         ARGS: "-rltgoDzvO"
  #         SOURCE: "dist/"
  #         REMOTE_HOST: ${{ secrets.SERVER_IP }}
  #         REMOTE_USER: ${{ secrets.ROOT }}
  #         TARGET: "/var/www/react/login/"
  #         EXCLUDE: "/dist/, /node_modules/"
